services:
  portfolio:
    container_name: portfolio

    build:
      context: .
      dockerfile: Dockerfile

    image: hemendra/portfolio:1.0.0

    expose:
      - "80"

    restart: unless-stopped

    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
